### ISSUE TITLE
Instructions to use this tool

### ISSUE THREAD

**Issue by satanu01** [gaomy3832/zsimparse#3]
Hi, Can you please provide some instructions that how to use this tool for parsing the trace files?

**Comment by gaomy3832** [comment]
The original zsim repo contains some simple examples about how to use python to parse the output h5 file, https://github.com/s5z/zsim/blob/master/README.stats. This tool is just a more structured wrapper for the same purpose. You can see some examples in the `tests` folder.

I am not sure what you mean by "trace files". If you are talking about the trace-based simulation, then this tool cannot help.
